# Generated by Django 4.2.5 on 2023-10-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="year_of_admission",
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
