# Generated by Django 4.2.5 on 2023-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_student_year_of_admission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="year_of_admission",
            field=models.PositiveIntegerField(verbose_name="Year of admission"),
        ),
    ]
