# Generated by Django 4.2.5 on 2023-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_group_teacher_middle_name_teacher_subject_and_more"),
        ("students", "0003_alter_student_year_of_admission"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ManyToManyField(related_name="student", to="teachers.group"),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_of_admission",
            field=models.PositiveIntegerField(verbose_name="year of admission"),
        ),
    ]
