# Generated by Django 4.2.5 on 2023-10-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="middle name"
                    ),
                ),
                ("surname", models.CharField(max_length=20, verbose_name="surname")),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=30, verbose_name="email")),
                ("subject", models.CharField(max_length=70, verbose_name="subject")),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=30, verbose_name="group name"),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.teacher",
                    ),
                ),
            ],
        ),
    ]
