# Generated by Django 4.2.5 on 2023-10-11 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_group_teacher_middle_name_teacher_subject_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeacherGroup",
        ),
    ]
